service: sb-gcp # Id of the service

env: flex       # Flex environment
runtime: java   # Java runtime
runtime_config:
  jdk: openjdk8 # use OpenJDK 8

handlers:
- url: /.*
  script: this field is required, but ignored

health_check:
  enable_health_check: true
  check_interval_sec: 10
  unhealthy_threshold: 5
  healthy_threshold: 1

env_variables:
  SPRING_DATA_MONGODB_URI: mongodb://10.156.0.3:27017,10.156.0.6:27017,10.156.0.5:27017/test?replicaSet=rs0