spring:
  application:
    name: sb-gcp
    
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
    rest:
      base-path: /api
    
management:
   context-path: /_ah
   security:
    enabled: false

  